### ISSUE TITLE
Tests pass or fail depending on test case ordering

### ISSUE THREAD

**Issue by enkore** [Qabel/qabel-accounting#94]
```
functional_tests/test_accounts.py ...
qabel_provider/test_admin.py .
qabel_provider/test_models.py .......
qabel_provider/test_rest.py ..........................

qabel_provider/test_admin.py .
qabel_provider/test_models.py .......
qabel_provider/test_rest.py ..........................
functional_tests/test_accounts.py F..
```

TB

```
_________ test_login _________

base_url = 'http://localhost:8081', user = <User: qabel_user>, browser = <splinter.driver.webdriver.phantomjs.WebDriver object at 0x7faba0562128>

    def test_login(base_url, user, browser):
        browser.visit('{0}/accounts/login/'.format(base_url))
        browser.fill_form({'username': 'qabel_user',
>                          'password': 'password'})

functional_tests/test_accounts.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ __ _ _ _ _ _
_venv/lib/python3.5/site-packages/splinter/driver/webdriver/__init__.py:421: in fill_form
    element = elements.first
_venv/lib/python3.5/site-packages/splinter/element_list.py:53: in first
    return self[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = [], index = 0

    def __getitem__(self, index):
        if not isinstance(index, int):
            return self.first[index]
        try:
            return super(ElementList, self).__getitem__(index)
        except IndexError:
            raise ElementDoesNotExist(
                u'no elements could be found with {0} "{1}"'.format(
>                   self.find_by, self.query))
E           splinter.exceptions.ElementDoesNotExist: no elements could be found with name "password"

_venv/lib/python3.5/site-packages/splinter/element_list.py:44: ElementDoesNotExist
-------------------------------- Captured stderr call ------
_venv/lib/python3.5/site-packages/django/template/defaulttags.py:499: RemovedInDjango110Warning: Reversing by dotted path is deprecated (django.contrib.auth.views.login).
  url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)

Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "_venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 507, in render
    current_app=current_app)
  File "_venv/lib/python3.5/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "_venv/lib/python3.5/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'qabel_id.django.contrib.auth.views.login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "_venv/lib/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "_venv/lib/python3.5/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "_venv/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "_venv/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "_venv/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "_venv/lib/python3.5/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "_venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "_venv/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "_venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "_venv/lib/python3.5/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "_venv/lib/python3.5/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'axes.decorators.decorated_login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

Instinct: It's probably because live_server is session-scoped and changes are made to the configuration which are not rolled back correctly.

**Comment by enkore** [comment]
Useful for detecting issues like this: https://github.com/klrmn/pytest-random

**Comment by jmt85** [comment]
remove functional test
