### ISSUE TITLE
Migration 0012_profile_block_quota.py  psycopg2.DataError: integer out of range

### ISSUE THREAD

**Issue by Rehwanne** [Qabel/qabel-accounting#98]
While applying the migrations i get the Following Error
```
./manage.py migrate
Operations to perform:
  Apply all migrations: admin, account, contenttypes, auth, sites, authtoken, qabel_provider, sessions, axes
Running migrations:
  Rendering model states... DONE
  Applying qabel_provider.0012_profile_block_quota...Traceback (most recent call last):
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 396, in add_field
    self.execute(sql, params)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/www/qabel-accounting/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

```

Maybe 
`field=models.IntegerField(default=2147483648, verbose_name='block server quota (in bytes)'),
`
should have been BigInt?

**Comment by enkore** [comment]
Yes. Yes it should. Thanks for the report.

**Comment by enkore** [comment]
Q: Does testing/prod run with pgsql instead of sqlite?
